apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-service
        image: ervmapa/backend:latest
        imagePullPolicy: Always
        name: backendhost
        ports:
        - containerPort: 5001
