apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:  # Correct indentation here
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-service
        - name: BACKEND_URL
          value: http://backend-service/update
        name: frontendhost
        image: ervmapa/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
