apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  ports:
  - nodePort: 30878
    port: 80
    targetPort: 5000
  selector:
    app: frontend
  type: NodePort
